!    SNEASY:  Simple Nonlinear EArth SYstem model, a composite of 
!               DOECLIM, Carbon Cycle, and MOC Boxmodel
!
!    Copyright (C) 2009  Klaus Keller, Nathan Urban, and Brian Tuttle
!
!    This program is free software; you can redistribute it and/or modify
!    it under the terms of the GNU General Public License as published by
!    the Free Software Foundation; either version 2 of the License, or
!    (at your option) any later version.
!
!    This program is distributed in the hope that it will be useful,
!    but WITHOUT ANY WARRANTY; without even the implied warranty of
!    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!    GNU General Public License for more details.
!
!    You should have received a copy of the GNU General Public License
!    along with this program; if not, write to the Free Software
!    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
!
!    Klaus Keller, klaus@psu.edu
!    Nathan Urban, nurban@princeton.edu
!    Brian Tuttle, btuttle@psu.edu
!
!===========================================================================

MODULE sneasy
!==============================================================================
!  This module couples the carbon cycle model CCM, climate model DOECLIM,
!  and an MOC box model to provide to DICE the global mean temperature and
!  the strength of the MOC, and to provide to a model written in R those
!  values as well as other time-series data generated by these component
!  models.
!
!==============================================================================

    USE global
    USE CCM
    USE doeclim
    USE moc_boxmodel
    USE rndseed
    USE mt19937

    implicit none

    private

    real(DP) :: timestep
    integer(i4b) :: start_year

    public :: init_SNES_arrays, dealloc_SNES
    public :: init_SNES_params, SNES_step, SNES_out

CONTAINS
!------------------------------------------------------------------------------
!SUBROUTINE init_SNES_arrays(Oc_anomaly_table)
SUBROUTINE init_SNES_arrays()
!  ==========================================================================
! |  Calculate the number of time steps for the earthsystem model.           |
! |  Default value for the start year is 1850 and may be replaced by the     |
! |  optional input parameter.                                               |
!  ==========================================================================

    implicit none

!    real(SP), dimension(:,:), intent(IN) :: Oc_anomaly_table

! Allocate arrays
    call alloc_SNES()

    call init_doeclim_arrays()

    call init_moc_boxmodel()

!    call init_CCM_arrays(Oc_anomaly_table)
    call init_CCM_arrays()

    RETURN

END SUBROUTINE init_SNES_arrays
!------------------------------------------------------------------------------

!!------------------------------------------------------------------------------
!SUBROUTINE init_ESys_arrays(nsteps, tstepsize, end_year, Oc_anomaly_table, &
!                            start_yr)
!!  ==========================================================================
!! |  Calculate the number of time steps for the earthsystem model.           |
!! |  Default value for the start year is 1850 and may be replaced by the     |
!! |  optional input parameter.                                               |
!!  ==========================================================================
!
!    implicit none
!
!    integer(i4b), intent(OUT) :: nsteps
!    real(DP), intent(IN) :: tstepsize
!    integer(i4b), intent(IN) :: end_year
!    real(SP), dimension(:,:), intent(IN) :: Oc_anomaly_table
!    integer(i4b), intent(IN), OPTIONAL :: start_yr
!
!  if (present(start_yr)) then
!    start_year = start_yr
!  else
!    start_year = 1850
!  end if
!
!    ns = int((end_year - start_year)/tstepsize) + 1
!
!! Output the global time step variable.
!    nsteps = ns
!
!! Make the time step size global to this module.
!    timestep = tstepsize
!
!! Allocate arrays
!    call alloc_SNES()
!
!    call init_doeclim_arrays(tstepsize)
!
!    call init_moc_boxmodel(tstepsize)
!
!    call init_CCM_arrays(tstepsize, Oc_anomaly_table)
!
!    RETURN
!
!END SUBROUTINE init_ESys_arrays
!!------------------------------------------------------------------------------

!------------------------------------------------------------------------------
SUBROUTINE init_SNES_params(Climate_sens, Ocean_vert_diff, Soil_respiration, &
                    Carbon_fertilization, Thermocline_diff, Hysens_NAsurf, &
                    MOCstrength_0, init_atm_CO2)
!  ==========================================================================
! |  For use with routines in R, this subroutine accepts as input            |
! |  initialization data that must be read from files or from startup        |
! |  parameters.                                                             |
!  ==========================================================================

    implicit none

    real(DP), intent(IN) :: Climate_sens
    real(DP), intent(IN) :: Ocean_vert_diff
    real(DP), intent(IN) :: Soil_respiration
    real(DP), intent(IN) :: Carbon_fertilization
    real(DP), intent(IN) :: Thermocline_diff
    real(DP), intent(IN) :: Hysens_NAsurf
    real(DP), intent(IN) :: MOCstrength_0
    real(DP), intent(IN), OPTIONAL :: init_atm_CO2

! MOC boxmodel input parameters: 
!    real(DP) :: Hysens_NAsurf = 0.047d0 ! hydrological sens, North Atl. surface
!    real(DP) :: MOCstrength_0 = 22.6d0
    real(DP) :: sigma_Tmp = 0.0d0
    real(DP) :: sigma_Sal = 0.0d0
    real(DP) :: MOC_str1

! Random number seed:
    integer(i4b), parameter :: max_seed_digits = 9
    integer(i4b) :: seed

! Initialize DOECLIM climate model parameters.
    call init_doeclim_parameters(Climate_sens, Ocean_vert_diff)

! Initialize CCM carbon cycle model parameters.
    call init_CCM_parameters(Climate_sens, Soil_respiration, &
                             Carbon_fertilization, Thermocline_diff)

    ! Overwrite default value with input parameter.
    if (present (init_atm_CO2)) atmco2(1) = init_atm_CO2

! Initialize MOC_boxmodel parameters.
!  Seed the random number generator, if it hasn't been already.
  if (.not. seeded) then 
    call randate(seed, max_seed_digits)
    call init_genrand(seed)
    seeded = .true.
  end if

    call init_moc_parameters(Hysens_NAsurf, MOCstrength_0, &
                             sigma_Tmp, sigma_Sal, MOC_str1)

    RETURN

END SUBROUTINE init_SNES_params
!------------------------------------------------------------------------------

!!------------------------------------------------------------------------------
!SUBROUTINE SNES(carbon_emis, MOC_strength, radiative_forc, ATM_CO2, &
!                atm_oc_flux, GL_surface_temp, GL_ocean_heat)
!!  ==========================================================================
!! |  Delivers ESys output as well as earth_system module global variables    |
!! |  as subroutine output parameters.  This is to interface with a calling   |
!! |  program without supplying access to the global variables of the module. |
!!  ==========================================================================
!
!    implicit none
!
!    real(DP), dimension(:), intent(IN) :: carbon_emis
!    real(DP), dimension(nsteps), intent(OUT) :: MOC_strength
!    real(DP), dimension(nsteps), intent(OUT) :: radiative_forc
!    real(DP), dimension(nsteps), intent(OUT) :: ATM_CO2
!    real(DP), dimension(nsteps), intent(OUT) :: atm_oc_flux
!    real(DP), dimension(nsteps), intent(OUT) :: GL_surface_temp
!    real(DP), dimension(nsteps), intent(OUT) :: GL_ocean_heat
!    integer(i4b) :: tx
!
!! Check size of input arrays.
!    if (size(carbon_emis) .ne. nsteps) then
!        print *, "ESys: carbon_emis input array size is incompatible with number of time steps."
!        return
!    end if
!
!! Step through the time series.
!    do tx=1,nsteps
!
!    ! Call the main earth_system subroutine.
!        call SNES_step(tx, carbon_emis(tx), MOC_strength(tx), &
!                       radiative_forc(tx), GL_surface_temp(tx))
!
!    end do
!
!! Assign values to output parameters from the component modules global vars.
!!  CCM:
!    ATM_CO2 = atmco2
!    atm_oc_flux = ocflux
!
!!  DOECLIM:
!    GL_ocean_heat = heat_interior
!
!
!    RETURN
!
!END SUBROUTINE SNES
!!------------------------------------------------------------------------------

!------------------------------------------------------------------------------
SUBROUTINE SNES_step(timex, CO2_emis, other_forcing, MOC_out, rad_forcing, &
                    temp_forcing)
!  ==========================================================================
! |  The main routine for the earth_system module.  It delivers the primary  |
! |  output via the subroutine output parameters.  The rest are available    |
! |  as module global variables.                                             |
!  ==========================================================================

    implicit none

    integer(i4b), intent(IN) :: timex                ! time index
    real(DP), intent(IN)  :: CO2_emis
    real(DP), intent(IN)  :: other_forcing           ! non-CO2 forcing
    real(DP), intent(OUT) :: MOC_out
    real(DP), intent(OUT) :: rad_forcing
    real(DP), intent(OUT) :: temp_forcing

! Calculate radiative forcing from atmospheric CO2 and non-CO2 forcing.
    rad_forcing = 3.7d0 * log(atmco2(timex)/atmco2(1))/log(2.0d0) + &
                    other_forcing

! Climate module takes rad_forcing and outputs temp_forcing to MOC and CCM.
    call doeclimtimestep_simple(timex, rad_forcing, temp_forcing)

! CC model takes temp_forcing and CO2 emissions and provides atmospheric
!  CO2 as a global variable.
    call CC_model(timex, temp_forcing, CO2_emis)

! MOC model takes temp_forcing and outputs damages.
    call moc_mod_var_forced(timex, temp_forcing, MOC_out)

    RETURN

END SUBROUTINE SNES_step
!------------------------------------------------------------------------------

!------------------------------------------------------------------------------
SUBROUTINE SNES_out()

    implicit none

    character(len=8) :: fname = 'ESys.out'
    integer(i4b) :: tx, istat
    real(SP) :: year
    integer(i4b) :: snesIOU = 40

    open (snesIOU,FILE=fname,STATUS='REPLACE',ACTION='WRITE',FORM='FORMATTED', &
            IOSTAT=istat)

    do tx = 1,nsteps
        year = start_year + timestep*(tx-1)
        write(snesIOU,'(f9.2,8es12.4)') year, temp_landair(tx), temp_sst(tx), &
                 heat_mixed(tx), heat_interior(tx), atmco2(tx), landflux(tx), &
                    atm_oc_flux(tx), emissions(tx)
    end do

    close(snesIOU)

    RETURN

END SUBROUTINE SNES_out
!------------------------------------------------------------------------------

!------------------------------------------------------------------------------
SUBROUTINE alloc_SNES()
!  ==========================================================================
! |  Allocate arrays for this module if needed.                              |
!  ==========================================================================
    
    implicit none

!    integer :: astat

!    astat = 0
!    allocate(temp_obs_dat(ntempdata), STAT=astat)
!    if (astat > 0) print *, "Problem with alloc_ESys."

    RETURN

END SUBROUTINE alloc_SNES
!------------------------------------------------------------------------------

!------------------------------------------------------------------------------
SUBROUTINE dealloc_SNES()
!  ==========================================================================
! |  Finalize and clean up earthsystem component module variables.           |
!  ==========================================================================
    
    implicit none

!    integer :: astat

!    astat = 0
!    deallocate(temp_obs_dat, STAT=astat)
!    if (astat > 0) print *, "Problem with dealloc_ESys."

    call dealloc_doeclim()
    call dealloc_CCM()
    call dealloc_moc()

    RETURN

END SUBROUTINE dealloc_SNES
!------------------------------------------------------------------------------
END MODULE sneasy
